spring:
  application:
    name: item-service
  sleuth:
    sampler:
      probability: 0.1
#设置禁止配置中心的配置
  cloud:
    config:
      override-none: true
# 启动参数 --server.port可以覆盖yml配置
server:
  port: 8001
#服务提供者向eureka注册信息
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip