spring:
  application:
    name: order-service
  sleuth:
    sampler:
      probability: 0.1
#设置禁止配置中心的配置
  cloud:
    config:
      override-none: true
server:
  port: 8201
#服务提供者向eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#feign启动hystrix降级，熔断
feign:
  hystrix:
    enabled: true
#暴露Hystrix监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
